# Generated by Django 5.2.11 on 2026-03-03 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0038_ratinginfopage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_team_name', models.CharField(max_length=255, verbose_name='Запрошенное название команды')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_team_claims', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.team', verbose_name='Выбранная команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка команды',
                'verbose_name_plural': 'Заявки команд',
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, help_text='Почему хочет в команду', verbose_name='Комментарий пилота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.driver', verbose_name='Пилот')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки на вступление',
                'unique_together': {('driver', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('captain', 'Капитан'), ('manager', 'Менеджер'), ('media', 'Медиа-менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='website.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_managers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Управляющий командой',
                'verbose_name_plural': 'Управляющие командами',
                'unique_together': {('user', 'team')},
            },
        ),
    ]
