# Generated by Django 5.2.17 on 2026-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teaminvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamclaim',
            name='requested_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Запрошенный город'),
        ),
    ]
