from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0005_stage_registration_fields'),
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_type', models.CharField(choices=[('pilot', 'Пилот'), ('team', 'Команда'), ('organizer', 'Организатор')], default='pilot', max_length=20)),
                ('start_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подана'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='draft', max_length=20)),
                ('organizer_comment', models.TextField(blank=True)),
                ('entry_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('race_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.raceclass')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizers.stage')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ApplicationApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('team', 'Команда'), ('individual', 'Физическое лицо')], default='individual', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название/ФИО')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Номер лицензии')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='№ договора')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('rep_first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя представителя')),
                ('rep_last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия представителя')),
                ('rep_email', models.EmailField(blank=True, max_length=254, verbose_name='Email представителя')),
                ('rep_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон представителя')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='applications.application')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.team')),
            ],
            options={'verbose_name': 'Заявитель'},
        ),
        migrations.CreateModel(
            name='ApplicationPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('citizenship', models.CharField(default='Россия', max_length=100, verbose_name='Гражданство')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sport_rank', models.CharField(blank=True, max_length=100, verbose_name='Спортивное звание')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Лицензия пилота')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, default='Россия', max_length=100, verbose_name='Страна')),
                ('parent_last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия родителя')),
                ('parent_first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя родителя')),
                ('parent_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество родителя')),
                ('parent_relation', models.CharField(blank=True, choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун/попечитель')], max_length=20, verbose_name='Кем приходится')),
                ('parent_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон родителя')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email родителя')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot', to='applications.application')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='website.driver')),
            ],
            options={'verbose_name': 'Пилот в заявке'},
        ),
        migrations.CreateModel(
            name='ApplicationKart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_brand', models.CharField(max_length=100, verbose_name='Марка шасси')),
                ('engine_1', models.CharField(max_length=100, verbose_name='Двигатель 1')),
                ('engine_2', models.CharField(blank=True, max_length=100, verbose_name='Двигатель 2')),
                ('tires', models.CharField(blank=True, max_length=100, verbose_name='Шины')),
                ('transponder_number', models.CharField(blank=True, max_length=50, verbose_name='Номер транспондера AMB')),
                ('ad_consent', models.BooleanField(default=True, verbose_name='Согласие на размещение рекламы')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kart', to='applications.application')),
            ],
            options={'verbose_name': 'Карт в заявке'},
        ),
        migrations.CreateModel(
            name='ApplicationMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Лицензия механика')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to='applications.application')),
            ],
            options={'verbose_name': 'Механик в заявке'},
        ),
        migrations.CreateModel(
            name='ApplicationAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=255, verbose_name='Соревнование')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('achievement', models.CharField(max_length=255, verbose_name='Достижение')),
                ('order', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='applications.application')),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Достижение пилота'},
        ),
        migrations.CreateModel(
            name='StageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('minors_only', models.BooleanField(default=False, verbose_name='Только для несовершеннолетних')),
                ('has_expiry_date', models.BooleanField(default=False, verbose_name='Есть срок действия')),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='organizers.stage')),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Требуемый документ', 'verbose_name_plural': 'Требуемые документы'},
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='application_docs/%Y/%m/', verbose_name='Файл')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('status', models.CharField(choices=[('pending', 'Ожидает загрузки'), ('uploaded', 'Загружен'), ('verified', 'Проверен ✓'), ('rejected', 'Отклонён ✗')], default='pending', max_length=20)),
                ('organizer_comment', models.TextField(blank=True, verbose_name='Комментарий организатора')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('stage_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted', to='applications.stagedocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Документ заявки'},
        ),
        migrations.CreateModel(
            name='StageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (₽)')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Обязательная')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='organizers.stage')),
            ],
            options={'ordering': ['order'], 'verbose_name': 'Доп. опция этапа', 'verbose_name_plural': 'Доп. опции этапа'},
        ),
        migrations.CreateModel(
            name='ApplicationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='applications.application')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.stageoption')),
            ],
            options={'verbose_name': 'Выбранная опция'},
        ),
        migrations.CreateModel(
            name='ApplicationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('method', models.CharField(choices=[('manual', 'Ручная оплата (квитанция)'), ('online', 'Онлайн оплата')], default='manual', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('uploaded', 'Квитанция загружена'), ('verified', 'Оплата подтверждена'), ('rejected', 'Отклонена'), ('refunded', 'Возвращена')], default='pending', max_length=20, verbose_name='Статус')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='Квитанция об оплате')),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Оплата заявки'},
        ),
    ]
