# Generated by Django 5.2.12 on 2026-05-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_payment_comment_status_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpilot',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
        ),
    ]
