# Generated by Django 5.2.12 on 2026-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_applicationpilot_country'),
        ('applications', '0003_championshipdocument_championshipoption'),
    ]

    operations = [
    ]
