# Generated by Django 5.2.12 on 2026-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_championshipdocument_championshipoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpilot',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
        ),
    ]
