# Generated by Django 5.2.12 on 2026-06-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_applicationpilot_country'),
        ('applications', '0004_merge_20260605_1201'),
    ]

    operations = [
    ]
