# Generated by Django 5.2.11 on 2026-03-10 13:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshippage',
            name='competition_types',
        ),
        migrations.CreateModel(
            name='ChampionshipCompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.competitiontype')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_competition_types', to='website.championshippage')),
            ],
            options={
                'verbose_name': 'Тип соревнования',
                'verbose_name_plural': 'Типы соревнований',
                'unique_together': {('page', 'competition_type')},
            },
        ),
    ]
