# Generated by Django 5.2.11 on 2026-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_team_logo_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='chassis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Шасси'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='race_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Стартовый номер'),
        ),
    ]
