# Generated by Django 5.2.11 on 2026-02-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_raceresult_chassis_raceresult_race_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceclass',
            options={'verbose_name': 'Класс гонки', 'verbose_name_plural': 'Классы гонок'},
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='raceclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название класса'),
        ),
    ]
