# Generated by Django 5.2.11 on 2026-02-13 17:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_raceclass_options_team_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='website.team'),
        ),
        migrations.CreateModel(
            name='DriverSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('network_name', models.CharField(max_length=100, verbose_name='Название (например: ВК, Instagram)')),
                ('link_url', models.URLField(verbose_name='Ссылка')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='website.driver')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
