# Generated by Django 5.2.11 on 2026-02-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_team_expire_at_team_expired_team_first_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='position_correction',
            field=models.PositiveIntegerField(blank=True, help_text='Заполните, если нужно вручную изменить позицию пилота (например, при равных очках)', null=True, verbose_name='Корректировка места'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_results', to='website.team', verbose_name='Команда'),
        ),
    ]
