# Generated by Django 5.2.14 on 2026-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_adfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambda_active', models.FloatField(default=0.8, help_text='Скорость затухания для пилотов с недавними гонками. Полураспад = ln(2)/λ лет. Рекомендуется 0.5–1.2.', verbose_name='λ активного пилота')),
                ('lambda_inactive', models.FloatField(default=2.0, help_text='Скорость затухания для пилотов без гонок дольше порога. Должен быть выше lambda_active. Рекомендуется 1.5–3.0.', verbose_name='λ неактивного пилота')),
                ('inactive_threshold_days', models.IntegerField(default=180, help_text='Количество дней без гонок в классе, после которого применяется lambda_inactive. Один летний сезон ≈ 180 дней.', verbose_name='Порог неактивности (дней)')),
                ('min_races_per_class', models.IntegerField(default=5, help_text='Класс с меньшим количеством гонок пропускается при расчёте BT.', verbose_name='Мин. гонок для расчёта класса')),
                ('min_comparisons', models.IntegerField(default=10, help_text='Класс с меньшим количеством парных сравнений пропускается.', verbose_name='Мин. парных сравнений (BT)')),
                ('min_starts_display', models.IntegerField(default=3, help_text='Пилоты с меньшим числом стартов считаются без достаточной статистики.', verbose_name='Мин. стартов для отображения рейтинга')),
                ('min_races_context', models.IntegerField(default=10, help_text='Класс с меньшим количеством гонок пропускается при расчёте контекстной модели.', verbose_name='Мин. гонок для контекстной модели')),
                ('min_comparisons_context', models.IntegerField(default=20, help_text='Класс с меньшим числом сравнений пропускается в контекстной модели.', verbose_name='Мин. парных сравнений (контекстная модель)')),
                ('bt_alpha', models.FloatField(default=0.1, help_text='Lasso-регуляризация Bradley-Terry. Выше → сильнее сглаживание к среднему для пилотов с малым числом гонок. Диапазон: 0.01–1.0.', verbose_name='Alpha (L1-регуляризация BT)')),
                ('pagerank_damping', models.FloatField(default=0.85, help_text='Коэффициент затухания PageRank. Стандартное значение 0.85. Диапазон: 0.5–0.99.', verbose_name='Damping factor (PageRank)')),
                ('ensemble_min_common_drivers', models.IntegerField(default=3, help_text='Минимальное число общих пилотов между BT и PageRank для построения ансамбля.', verbose_name='Мин. общих пилотов для ансамбля')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки аналитики',
                'verbose_name_plural': 'Настройки аналитики',
            },
        ),
    ]
