# Generated by Django 5.2.12 on 2026-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_adfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
