# Generated by Django 5.2.12 on 2026-05-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_analytics_settings'),
        ('website', '0007_analyticstask'),
    ]

    operations = [
    ]
