# Generated by Django 5.2.11 on 2026-02-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_raceresult_position_correction_alter_raceresult_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='position_correction',
        ),
        migrations.AddField(
            model_name='raceresult',
            name='tie_breaker',
            field=models.FloatField(default=0, help_text='Скрытые очки для разрешения равенства (не отображаются на сайте)', verbose_name='Тай-брейк'),
        ),
    ]
