# Generated by Django 5.2.12 on 2026-05-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_merge_0007_analytics_settings_0007_analyticstask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsTask',
        ),
    ]
