# Generated by Django 5.2.11 on 2026-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_raceresult_position_correction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceclassresultgroup',
            options={'verbose_name': 'Группа результатов', 'verbose_name_plural': 'Группы результатов'},
        ),
        migrations.AddField(
            model_name='eventpage',
            name='admin_title',
            field=models.CharField(blank=True, help_text="Короткое название для отображения в списках админки (например, '1 этап Micro')", max_length=255, verbose_name='Название для админки'),
        ),
    ]
