# Generated by Django 5.2.11 on 2026-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_eventpage_admin_title_track_eventpage_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='address',
            field=models.CharField(blank=True, help_text='Улица, дом', max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
