# Generated by Django 5.2.12 on 2026-06-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_analytics_settings_trend_window'),
        ('website', '0011_techarticleindexpage'),
    ]

    operations = [
    ]
