# Generated by Django 5.2.11 on 2026-02-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_track_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='map_html',
            field=models.TextField(blank=True, help_text='HTML-код для вставки карты (например, iframe с Яндекс.Картами)', null=True, verbose_name='Код карты'),
        ),
    ]
