# Generated by Django 5.2.12 on 2026-06-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_teammembership_race_class'),
        ('website', '0012_merge_20260604_1525'),
    ]

    operations = [
    ]
