# Generated by Django 5.2.12 on 2026-06-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_add_qual_and_prefinal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='best_lap_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Круг, мс'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='penalty',
            field=models.FloatField(default=0, verbose_name='Штраф'),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='tie_breaker',
            field=models.FloatField(default=0, verbose_name='Тай-брейк'),
        ),
    ]
