# Generated by Django 5.2.12 on 2026-06-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20260605_1346'),
        ('website', '0014_add_roles_team_pushtoken'),
    ]

    operations = [
    ]
