# Generated by Django 5.2.11 on 2026-02-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_chassis_chassissociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='chassis',
        ),
        migrations.AddField(
            model_name='raceresult',
            name='chassis_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_results', to='website.chassis', verbose_name='Шасси (связанное)'),
        ),
    ]
