# Generated by Django 5.2.12 on 2026-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_pulsecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshippage',
            name='calendar_color',
            field=models.CharField(default='#ffc107', help_text='HEX-код цвета ячейки в общем календаре, например #ffc107', max_length=7, verbose_name='Цвет в календаре'),
        ),
    ]
