# Generated by Django 5.2.11 on 2026-02-17 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_engine_raceclassresultgroup_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='air_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура воздуха, °C'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Влажность, %'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Давление, мм рт. ст.'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='race_time',
            field=models.TimeField(default=datetime.time(14, 0), help_text='Время проведения заезда (по умолчанию 14:00)', verbose_name='Время заезда'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='uv_index',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-индекс'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость ветра, м/с'),
        ),
        migrations.AddField(
            model_name='track',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Например: 43.5347 (для Сочи)', null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='track',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Например: 39.8555 (для Сочи)', null=True, verbose_name='Долгота'),
        ),
    ]
