# Generated by Django 5.2.12 on 2026-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_add_championship_calendar_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshippage',
            name='calendar_color',
        ),
        migrations.AddField(
            model_name='stagepage',
            name='calendar_color',
            field=models.CharField(default='#ffc107', help_text='Цвет ячейки в общем календаре для этого этапа', max_length=7, verbose_name='Цвет в календаре'),
        ),
    ]
