# Generated by Django 5.2.11 on 2026-02-17 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_raceresult_air_temperature_raceresult_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='air_temperature',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='uv_index',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='air_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура воздуха, °C'),
        ),
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Влажность, %'),
        ),
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='pressure',
            field=models.IntegerField(blank=True, null=True, verbose_name='Давление, мм рт. ст.'),
        ),
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='race_time',
            field=models.TimeField(default=datetime.time(14, 0), help_text='Время проведения заезда для этого класса (по умолчанию 14:00)', verbose_name='Время заезда'),
        ),
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='uv_index',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-индекс'),
        ),
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость ветра, м/с'),
        ),
    ]
