# Generated by Django 5.2.12 on 2026-07-07 18:31

from django.db import migrations, models


def reset_untouched_default_color(apps, schema_editor):
    """Миграция 0018 проставила '#ffc107' абсолютно всем StagePage (побочный эффект AddField
    с default). Сбрасываем это обратно в '' (не задан), чтобы такие этапы стали наследовать
    цвет чемпионата, а не считались «явно выбравшими жёлтый»."""
    StagePage = apps.get_model('website', 'StagePage')
    StagePage.objects.filter(calendar_color='#ffc107').update(calendar_color='')


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_move_calendar_color_to_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshippage',
            name='calendar_color',
            field=models.CharField(blank=True, default='', help_text='Цвет по умолчанию для всех этапов чемпионата, у которых цвет не задан индивидуально', max_length=7, verbose_name='Цвет в календаре'),
        ),
        migrations.AlterField(
            model_name='stagepage',
            name='calendar_color',
            field=models.CharField(blank=True, default='', help_text='Если не задан — используется цвет чемпионата', max_length=7, verbose_name='Цвет в календаре'),
        ),
        migrations.RunPython(reset_untouched_default_color, migrations.RunPython.noop),
    ]
