# Generated by Django 5.2.12 on 2026-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_inherit_calendar_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(blank=True, help_text='Например: @gripline_channel или числовой chat_id.', max_length=64, verbose_name='Channel ID')),
                ('tag_matchast', models.CharField(default='#матчасть', max_length=32, verbose_name='Тег — Матчасть')),
                ('emoji_matchast', models.CharField(default='🔧', max_length=8, verbose_name='Эмодзи — Матчасть')),
                ('tag_news', models.CharField(default='#новости', max_length=32, verbose_name='Тег — Новости')),
                ('emoji_news', models.CharField(default='🏁', max_length=8, verbose_name='Эмодзи — Новости')),
            ],
            options={
                'verbose_name': 'Настройки Telegram',
                'verbose_name_plural': 'Настройки Telegram',
            },
        ),
    ]
