# Generated by Django 5.2.11 on 2026-02-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_raceresult_air_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceclassresultgroup',
            name='precipitation',
            field=models.FloatField(blank=True, help_text='Количество осадков за час (0 - сухо, >0 - дождь)', null=True, verbose_name='Осадки, мм'),
        ),
    ]
