# Generated by Django 5.2.12 on 2026-08-10 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_add_telegram_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='telegram_posted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='telegram_posted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='telegram_teaser',
            field=models.TextField(blank=True, help_text='Короткий тизер для Telegram (3–5 предложений). Лимит ~900 символов — оставляет запас под ссылку и подпись к фото (Telegram ограничивает подпись к фото 1024 символами).', max_length=900, verbose_name='Тизер для Telegram'),
        ),
    ]
