# Generated by Django 5.2.12 on 2026-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_add_telegram_fields_to_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='link_text',
            field=models.CharField(default='Читать статью →', help_text='Показывается вместо длинного URL в тексте поста.', max_length=64, verbose_name='Текст ссылки на статью'),
        ),
    ]
