# Generated by Django 5.2.11 on 2026-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_driver_rating_score_driver_rating_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='rating_score',
            field=models.FloatField(default=0.0, help_text='Рассчитывается аналитической моделью', verbose_name='Рейтинг (Брэдли-Терри)'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='rating_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления рейтинга'),
        ),
    ]
