# Generated by Django 5.2.11 on 2026-02-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_chassis_rating_score_chassis_rating_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating_by_class',
            field=models.JSONField(blank=True, default=dict, help_text="Формат: {'class_id': {'score': 35.2, 'starts': 5, 'updated': '2024-01-01'}}", verbose_name='Рейтинги по классам'),
        ),
    ]
