# Generated by Django 5.2.11 on 2026-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_driver_rating_by_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='pagerank_score',
            field=models.FloatField(default=0.0, help_text='Модифицированный PageRank', verbose_name='Рейтинг (PageRank)'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='pagerank_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления PageRank'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pagerank_by_class',
            field=models.JSONField(blank=True, default=dict, help_text="Формат: {'class_id': {'score': 0.15, 'starts': 5}}", verbose_name='PageRank по классам'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pagerank_score',
            field=models.FloatField(default=0.0, help_text='Модифицированный PageRank - учитывает силу расписания', verbose_name='Рейтинг (PageRank)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pagerank_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления PageRank'),
        ),
    ]
