# Generated by Django 5.2.11 on 2026-02-19
# Миграция для добавления полей ансамбля

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_chassis_pagerank_score_chassis_pagerank_updated_at_and_more'),
    ]

    operations = [
        # Добавляем поля для ансамбля в Chassis
        migrations.AddField(
            model_name='chassis',
            name='ensemble_score',
            field=models.FloatField(default=0.0, help_text='Комбинация Брэдли-Терри и PageRank', verbose_name='Рейтинг (Ансамбль)'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='ensemble_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления ансамбля'),
        ),

        # Добавляем поля для ансамбля в Driver
        migrations.AddField(
            model_name='driver',
            name='ensemble_by_class',
            field=models.JSONField(blank=True, default=dict, help_text="Формат: {'class_id': {'score': 0.75, 'starts': 5}}", verbose_name='Ансамбль по классам'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ensemble_score',
            field=models.FloatField(default=0.0, help_text='Комбинация Брэдли-Терри и PageRank', verbose_name='Рейтинг (Ансамбль)'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ensemble_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления ансамбля'),
        ),
    ]
