# Generated by Django 5.2.11 on 2026-02-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_weightspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.DateTimeField(blank=True, null=True, verbose_name='Значение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Метаданные аналитики',
                'verbose_name_plural': 'Метаданные аналитики',
            },
        ),
    ]
