# Generated by Django 5.2.11 on 2026-02-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_analyticsmetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='race_time',
        ),
    ]
