# Generated by Django 5.2.12 on 2026-08-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_articlepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='LapPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pre_final', 'Предфинал'), ('final', 'Финал')], max_length=16)),
                ('lap', models.PositiveSmallIntegerField(verbose_name='Круг (0 = старт)')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_positions', to='website.driver')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_positions', to='website.raceclassresultgroup')),
            ],
            options={
                'verbose_name': 'Позиция по кругу',
                'verbose_name_plural': 'Позиции по кругам',
                'indexes': [models.Index(fields=['group', 'session_type'], name='website_lap_group_i_09497b_idx')],
                'unique_together': {('group', 'driver', 'session_type', 'lap')},
            },
        ),
    ]
