# Generated by Django 5.2.11 on 2026-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_raceresult_race_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('status', models.CharField(default='success', max_length=50, verbose_name='Статус')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Лог обновления',
                'verbose_name_plural': 'Логи обновлений',
                'ordering': ['-updated_at'],
            },
        ),
    ]
