# Generated by Django 5.2.12 on 2026-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_add_lap_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_api_url', models.URLField(default='https://archive-api.open-meteo.com/v1/archive', help_text='Исторические данные — для прошедших этапов.', verbose_name='URL архивного API')),
                ('forecast_api_url', models.URLField(default='https://api.open-meteo.com/v1/forecast', help_text='Прогноз — для этапов в пределах горизонта прогноза.', verbose_name='URL API прогноза')),
                ('timezone', models.CharField(default='Europe/Moscow', help_text='Передаётся в Open-Meteo как параметр timezone (IANA-имя).', max_length=64, verbose_name='Часовой пояс')),
                ('forecast_horizon_days', models.PositiveSmallIntegerField(default=15, help_text='За пределами — используется статистическая оценка по прошлым годам.', verbose_name='Горизонт прогноза, дней')),
                ('climatology_years', models.PositiveSmallIntegerField(default=5, help_text='Сколько прошлых лет усредняется для оценки погоды, если этап дальше горизонта прогноза.', verbose_name='Лет для статистической оценки')),
                ('day_start_hour', models.PositiveSmallIntegerField(default=9, help_text='Нижняя граница часового диапазона для сводки погоды на день этапа.', verbose_name='Начало дня, час')),
                ('day_end_hour', models.PositiveSmallIntegerField(default=18, help_text='Верхняя граница часового диапазона для сводки погоды на день этапа.', verbose_name='Конец дня, час')),
            ],
            options={
                'verbose_name': 'Настройки погоды',
                'verbose_name_plural': 'Настройки погоды',
            },
        ),
    ]
