# Generated by Django 5.2.12 on 2026-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_add_weather_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='final_status',
            field=models.CharField(blank=True, choices=[('DNF', 'DNF — не финишировал'), ('DQ', 'DQ — дисквалифицирован'), ('DNS', 'DNS — не стартовал')], default='', max_length=3, verbose_name='Статус финала'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='pre_final_status',
            field=models.CharField(blank=True, choices=[('DNF', 'DNF — не финишировал'), ('DQ', 'DQ — дисквалифицирован'), ('DNS', 'DNS — не стартовал')], default='', max_length=3, verbose_name='Статус предфинала'),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='qual_status',
            field=models.CharField(blank=True, choices=[('DNF', 'DNF — не финишировал'), ('DQ', 'DQ — дисквалифицирован'), ('DNS', 'DNS — не стартовал')], default='', max_length=3, verbose_name='Статус квалификации'),
        ),
    ]
