# Generated by Django 5.2.11 on 2026-02-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_pulseindexpage_championshippage_champion_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshippage',
            name='champion_driver',
        ),
        migrations.RemoveField(
            model_name='championshippage',
            name='year',
        ),
    ]
