# Generated by Django 5.2.12 on 2026-08-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_raceresult_final_status_raceresult_pre_final_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshippage',
            name='standings_cache',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Кэш турнирных таблиц'),
        ),
    ]
