# Generated by Django 5.2.11 on 2026-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_championshippage_champion_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='penalty',
            field=models.FloatField(default=0, help_text='Штрафные баллы (вычитаются из очков)', verbose_name='Штраф'),
        ),
    ]
