# Generated by Django 5.2.12 on 2026-08-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_championshippage_standings_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='records_cache',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Рекорды трасс (пересчитываемые)'),
        ),
    ]
