# Generated by Django 5.2.12 on 2026-08-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_track_records_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='mediakit_top10_min_field',
            field=models.IntegerField(default=15, help_text='Медиа-кит показывает бейдж «стабильно топ-10» только если типичный размер стартового поля пилота в классе не меньше этого значения — иначе формулировка была бы нечестной. Порог для «топ-5» берётся вдвое меньшим.', verbose_name='Мин. размер поля для «топ-10» в медиа-ките'),
        ),
    ]
