# Generated by Django 5.2.11 on 2026-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_fix_competition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код (cup, championship, competition)')),
            ],
            options={
                'verbose_name': 'Тип соревнований',
                'verbose_name_plural': 'Типы соревнований',
            },
        ),
        migrations.RemoveField(
            model_name='championshippage',
            name='competition_type',
        ),
        migrations.AddField(
            model_name='championshippage',
            name='competition_types',
            field=models.ManyToManyField(blank=True, help_text='Выберите один или несколько типов', related_name='championships', to='website.competitiontype', verbose_name='Типы соревнований'),
        ),
    ]
