# Generated by Django 5.2.12 on 2026-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_analyticssettings_mediakit_top10_min_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город / база'),
        ),
    ]
