# Generated by Django 5.2.11 on 2026-03-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_competitiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshippage',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Отметьте, если все этапы проведены', verbose_name='Чемпионат завершён'),
        ),
    ]
