# Generated by Django 5.2.12 on 2026-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_team_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('front_rear', 'Перед/зад, %'), ('left_right', 'Лево/право, %'), ('cross_weight', 'Cross weight, %')], max_length=20, unique=True, verbose_name='Метрика')),
                ('green_min', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Зелёная зона, от')),
                ('green_max', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Зелёная зона, до')),
                ('yellow_min', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Жёлтая зона, от')),
                ('yellow_max', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Жёлтая зона, до')),
            ],
            options={
                'verbose_name': 'Порог цветовой индикации',
                'verbose_name_plural': 'Пороги цветовой индикации',
            },
        ),
        migrations.CreateModel(
            name='ChassisTypePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_type', models.CharField(choices=[('junior', 'Детское'), ('senior', 'Взрослое')], max_length=10, unique=True, verbose_name='Тип шасси')),
                ('wheelbase_mm', models.PositiveIntegerField(verbose_name='Колёсная база, мм')),
                ('track_front_mm', models.PositiveIntegerField(verbose_name='Колея перед, мм')),
                ('track_rear_mm', models.PositiveIntegerField(verbose_name='Колея зад, мм')),
            ],
            options={
                'verbose_name': 'Пресет геометрии шасси',
                'verbose_name_plural': 'Пресеты геометрии шасси',
            },
        ),
        migrations.CreateModel(
            name='KartClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('chassis_type', models.CharField(choices=[('junior', 'Детское'), ('senior', 'Взрослое')], help_text='Определяет, для каких картов доступен этот класс.', max_length=10, verbose_name='Тип шасси')),
                ('min_weight_kg', models.DecimalField(decimal_places=1, help_text='Карт + пилот + экипировка.', max_digits=5, verbose_name='Минимальный вес, кг')),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, help_text='Переопределение пресета типа шасси. Пусто — берётся пресет.', null=True, verbose_name='Колёсная база, мм')),
                ('track_front_mm', models.PositiveIntegerField(blank=True, help_text='Переопределение пресета типа шасси. Пусто — берётся пресет.', null=True, verbose_name='Колея перед, мм')),
                ('track_rear_mm', models.PositiveIntegerField(blank=True, help_text='Переопределение пресета типа шасси. Пусто — берётся пресет.', null=True, verbose_name='Колея зад, мм')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Класс (развесовка)',
                'verbose_name_plural': 'Классы (развесовка)',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
