# Generated by Django 5.2.12 on 2026-08-31 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_balancethreshold_chassistypepreset_kartclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Произвольная метка, например «Карт №1», «Синий Tony».', max_length=100, verbose_name='Название')),
                ('chassis_type', models.CharField(choices=[('junior', 'Детское'), ('senior', 'Взрослое')], help_text='У справочника «Шасси» такого признака нет — указывается здесь вручную.', max_length=10, verbose_name='Тип шасси')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель рамы')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chassis', models.ForeignKey(help_text='Существующий справочник шасси сайта.', on_delete=django.db.models.deletion.PROTECT, related_name='balance_karts', to='website.chassis', verbose_name='Шасси')),
                ('owner_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_karts', to='website.driver', verbose_name='Владелец-пилот')),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_karts', to='website.team', verbose_name='Владелец-команда')),
            ],
            options={
                'verbose_name': 'Карт (развесовка)',
                'verbose_name_plural': 'Карты (развесовка)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например «Мячково, сухо, полбака».', max_length=150, verbose_name='Название')),
                ('weight_lf', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Левый перед, кг')),
                ('weight_rf', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Правый перед, кг')),
                ('weight_lr', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Левый зад, кг')),
                ('weight_rr', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Правый зад, кг')),
                ('driver_weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Подставляется из ростера/профиля пилота, можно переопределить.', max_digits=5, null=True, verbose_name='Вес пилота, кг')),
                ('weather', models.CharField(choices=[('dry', 'Сухо'), ('wet', 'Дождь'), ('mixed', 'Переменная')], default='dry', max_length=10, verbose_name='Погода')),
                ('temp_air_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура воздуха, °C')),
                ('temp_track_c', models.DecimalField(blank=True, decimal_places=1, help_text='Только ручной ввод — погодные API её не дают.', max_digits=4, null=True, verbose_name='Температура покрытия, °C')),
                ('temp_source', models.CharField(choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], default='manual', max_length=10, verbose_name='Источник температуры')),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Колёсная база, мм')),
                ('track_front_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Колея перед, мм')),
                ('track_rear_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Колея зад, мм')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('shared_with_team', models.BooleanField(default=False, verbose_name='Открыт команде')),
                ('shared_with_driver', models.BooleanField(default=False, verbose_name='Открыт пилоту')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='website.kart', verbose_name='Карт')),
                ('kart_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setups', to='website.kartclass', verbose_name='Класс')),
                ('parent_setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='website.setup', verbose_name='Копия из')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_setups', to='website.track', verbose_name='Трасса')),
            ],
            options={
                'verbose_name': 'Сетап (развесовка)',
                'verbose_name_plural': 'Сетапы (развесовка)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ballast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Вес, кг')),
                ('pos_x_mm', models.DecimalField(decimal_places=1, help_text='От левого края колеи.', max_digits=6, verbose_name='Поперёк, мм')),
                ('pos_y_mm', models.DecimalField(decimal_places=1, help_text='От передней оси.', max_digits=6, verbose_name='Вдоль, мм')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Метка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballasts', to='website.setup', verbose_name='Сетап')),
            ],
            options={
                'verbose_name': 'Груз на схеме',
                'verbose_name_plural': 'Грузы на схеме',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('label', models.CharField(blank=True, help_text='Для различения однофамильцев, например «синий шлем», «старший».', max_length=100, verbose_name='Метка')),
                ('gear_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес в экипировке, кг')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Заполняется, когда пилот регистрируется и его DriverClaim подтверждён — вся история сетапов сохраняется.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_roster_entries', to='website.driver', verbose_name='Профиль пилота')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_roster_entries', to='website.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Запись ростера (развесовка)',
                'verbose_name_plural': 'Ростер (развесовка)',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='kart',
            name='roster_entry',
            field=models.ForeignKey(blank=True, help_text='За кем из ростера закреплён — только для карта команды.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karts', to='website.teamrosterentry', verbose_name='Закреплён за'),
        ),
        migrations.AddConstraint(
            model_name='kart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_driver__isnull', False), ('owner_team__isnull', True)), models.Q(('owner_driver__isnull', True), ('owner_team__isnull', False)), _connector='OR'), name='balance_kart_exactly_one_owner'),
        ),
    ]
