# Generated by Django 5.2.12 on 2026-08-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_kart_setup_ballast_teamrosterentry_kart_roster_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDiagnosticRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('front_high', 'Перед > верхней жёлтой границы'), ('front_low', 'Перед < нижней жёлтой границы'), ('cross_diagonal', 'Cross не идеален при нормальном L/R'), ('cross_mechanical', 'Cross за пределами жёлтой зоны'), ('lr_asymmetry', 'L/R за пределами жёлтой зоны'), ('wet_weather', 'Погода: дождь'), ('under_min_weight', 'Не набрана минималка класса'), ('why_43_57_target', 'Обучающий блок: почему 43/57')], max_length=30, unique=True, verbose_name='Условие')),
                ('text', models.TextField(help_text='Для "Не набрана минималка класса" доступна подстановка {shortfall_kg}.', verbose_name='Текст')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.articlepage', verbose_name='Статья Матчасти («Подробнее»)')),
            ],
            options={
                'verbose_name': 'Правило диагностики (развесовка)',
                'verbose_name_plural': 'Правила диагностики (развесовка)',
                'ordering': ['condition'],
            },
        ),
    ]
