# Generated by Django 5.2.11 on 2026-03-03 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0039_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email руководителя'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото руководителя'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_social',
            field=models.URLField(blank=True, help_text='Ссылка на VK, Telegram и т.д.', verbose_name='Соцсети руководителя'),
        ),
    ]
