# Generated by Django 5.2.12 on 2026-09-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_seed_balance_diagnostic_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raceclass',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Класс гонки', 'verbose_name_plural': 'Классы гонок'},
        ),
        migrations.AddField(
            model_name='raceclass',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Определяет место класса во всех фильтрах/вкладках по классам на сайте (вместо сортировки по алфавиту). Меньше значение — выше в списке.', verbose_name='Порядок сортировки'),
        ),
    ]
