# Generated by Django 5.2.11 on 2026-03-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_team_manager_email_team_manager_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Дата ухода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='website.driver')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='website.team')),
            ],
            options={
                'verbose_name': 'Участие в команде',
                'verbose_name_plural': 'Участия в командах',
                'unique_together': {('driver', 'team', 'joined_at')},
            },
        ),
    ]
