# Generated by Django 5.2.11 on 2026-03-04 12:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0041_teammembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('position', models.CharField(blank=True, help_text='например: Старший механик, тренер', max_length=255, verbose_name='Должность')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Сотрудник команды',
                'verbose_name_plural': 'Сотрудники команд',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamStaffSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('network_name', models.CharField(max_length=100, verbose_name='Название (например: ВК, Instagram)')),
                ('link_url', models.URLField(verbose_name='Ссылка')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='website.teamstaff')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamStaffMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Дата ухода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='website.teamstaff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='website.team')),
            ],
            options={
                'verbose_name': 'Участие сотрудника в команде',
                'verbose_name_plural': 'Участия сотрудников в командах',
                'unique_together': {('staff', 'team', 'joined_at')},
            },
        ),
    ]
