# Generated by Django 5.2.11 on 2026-03-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_teamstaff_teamstaffsociallink_teamstaffmembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstaffmembership',
            unique_together={('staff', 'team', 'is_active')},
        ),
    ]
