# Generated by Django 5.2.17 on 2026-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_seed_raceclass_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Кил-свитч. Выключить — немедленно останавливает всю исходящую почту приложения (уведомления, письма подтверждения) без деплоя. Использовать при компрометации почтового ящика.', verbose_name='Отправка писем включена')),
                ('host', models.CharField(default='smtp.yandex.ru', max_length=255, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP порт')),
                ('use_tls', models.BooleanField(default=True, help_text='Для порта 587. Взаимоисключимо с SSL ниже.', verbose_name='STARTTLS (use_tls)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Для порта 465. Взаимоисключимо с STARTTLS выше.', verbose_name='SSL (use_ssl)')),
                ('timeout', models.PositiveIntegerField(default=5, verbose_name='Таймаут соединения, сек')),
                ('host_user', models.CharField(blank=True, help_text='Пусто = переменная окружения EMAIL_HOST_USER на сервере.', max_length=255, verbose_name='Логин SMTP (адрес ящика)')),
                ('host_password', models.CharField(blank=True, help_text='Пусто = переменная окружения EMAIL_HOST_PASSWORD на сервере. Хранится в БД открытым текстом (как yandex_client_secret у SocialAuthSettings) — доступ только у пользователей с правами в Wagtail admin.', max_length=255, verbose_name='Пароль SMTP')),
                ('default_from_email', models.CharField(blank=True, help_text='Пусто = settings.DEFAULT_FROM_EMAIL. Формат: "Gripline <адрес@домен>".', max_length=255, verbose_name='From (адрес отправителя)')),
                ('admin_notify_email', models.EmailField(blank=True, help_text='Куда падают уведомления о новых заявках (привязка пилота/команды). Пусто = gripline.ru@yandex.ru (прежнее поведение).', max_length=254, verbose_name='Адрес для уведомлений администратору')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки почты',
                'verbose_name_plural': 'Настройки почты',
            },
        ),
    ]
