# Generated by Django 5.2.11 on 2026-03-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_alter_teamstaffmembership_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstaffmembership',
            unique_together={('staff', 'team')},
        ),
    ]
