# Generated by Django 5.2.17 on 2026-09-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_mailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='proxy_url',
            field=models.CharField(blank=True, help_text='Используется только если галочка выше включена. Пусто = переменная окружения EMAIL_PROXY_URL на сервере (по умолчанию тот же прокси, что и для Telegram). Формат: socks5h://host:port.', max_length=255, verbose_name='URL SOCKS5-прокси'),
        ),
        migrations.AddField(
            model_name='mailsettings',
            name='use_proxy',
            field=models.BooleanField(default=False, help_text='По умолчанию выключено — прямое соединение. Хостинг-провайдер блокирует исходящий SMTP (587/465) на сетевом уровне независимо от прокси/VPN (диагностировано 22.09.2026 — см. gripline_tz_zaschita_pochty.md), поэтому включать смысл есть только если это подтверждённо помогает в вашей конкретной сети. Переключается без деплоя — для быстрых экспериментов, не заводя новую переменную окружения на каждый тест.', verbose_name='Слать через SOCKS5-прокси (Xray/VPN-туннель)'),
        ),
    ]
