# Generated by Django 5.2.17 on 2026-09-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_mailsettings_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_url', models.CharField(blank=True, help_text='Локальный SOCKS5-листенер Xray на сервере. Пусто = переменная окружения TELEGRAM_PROXY_URL (историческое имя — прокси заводился изначально только для Telegram). Формат: socks5h://host:port.', max_length=255, verbose_name='URL SOCKS5-прокси')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки VPN',
                'verbose_name_plural': 'Настройки VPN',
            },
        ),
        migrations.RemoveField(
            model_name='mailsettings',
            name='proxy_url',
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='use_vpn',
            field=models.BooleanField(default=True, help_text='Хостинг блокирует прямые соединения к api.telegram.org — без этого анонс-постинг не работает. Адрес прокси — в разделе «VPN» (VpnSettings), не здесь. Включено по умолчанию — повторяет текущее рабочее поведение.', verbose_name='Использовать Xray/VPN'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='use_proxy',
            field=models.BooleanField(default=False, help_text='По умолчанию выключено — прямое соединение. Хостинг-провайдер блокирует исходящий SMTP (587/465) на сетевом уровне независимо от прокси/VPN (диагностировано 22.09.2026 — см. gripline_tz_zaschita_pochty.md), поэтому включать смысл есть только если это подтверждённо помогает в вашей конкретной сети. Адрес прокси — в разделе «VPN» (VpnSettings), не здесь. Переключается без деплоя.', verbose_name='Использовать Xray/VPN'),
        ),
    ]
