# Generated by Django 5.2.17 on 2026-09-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_vpnsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsettings',
            name='use_proxy',
            field=models.BooleanField(default=False, help_text='По умолчанию выключено — прямое соединение. IP сервера внесён в белый список хостинг-провайдера по SMTP (587/465), поэтому включать прокси в норме не требуется. Адрес прокси — в разделе «VPN» (VpnSettings), не здесь. Переключается без деплоя — оставлено как аварийный рубильник на случай повторной блокировки в будущем.', verbose_name='Использовать Xray/VPN'),
        ),
    ]
