# Generated by Django 5.2.17 on 2026-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_update_mailsettings_use_proxy_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('deletion', 'Удаление данных'), ('correction', 'Уточнение данных'), ('stop_processing', 'Прекращение обработки'), ('consent_withdrawal', 'Отзыв согласия')], max_length=20, verbose_name='Тип обращения')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на страницу')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт для ответа')),
                ('text', models.TextField(blank=True, verbose_name='Текст обращения')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Заявитель подтвердил, что он субъект ПД или его законный представитель')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('done', 'Рассмотрено'), ('rejected', 'Отклонено')], default='new', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Ответить до')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('admin_note', models.TextField(blank=True, help_text='Что сделано по обращению. После рассмотрения очистите «Контакт» и «Текст» (политика п. 6.1 — данные заявителя хранятся только на время рассмотрения).', verbose_name='Решение / заметка')),
            ],
            options={
                'verbose_name': 'Обращение по персональным данным',
                'verbose_name_plural': 'Обращения по персональным данным',
                'ordering': ['-created_at'],
            },
        ),
    ]
