# Generated by Django 5.2.17 on 2026-10-06 16:40

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_datarequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Бот включён')),
                ('bot_token_encrypted', models.TextField(blank=True, editable=False, verbose_name='Токен бота (шифртекст)')),
                ('bot_username', models.CharField(blank=True, default='gripline_support_bot', help_text='Без @. Telegram требует, чтобы юзернейм бота заканчивался на «bot». Используется в deep links с сайта.', max_length=64, verbose_name='Юзернейм бота')),
                ('use_vpn', models.BooleanField(default=True, help_text='Прод блокирует прямые соединения к api.telegram.org. Адрес прокси — в разделе «VPN» (VpnSettings), не здесь. Снять галочку = прямое соединение.', verbose_name='Использовать Xray/VPN')),
                ('admin_chat_id', models.BigIntegerField(blank=True, help_text='Закрытая супергруппа модерации (отрицательное число вида -100…). Для тем по категориям в группе должны быть включены «Темы».', null=True, verbose_name='ID админ-чата')),
                ('settings_refresh_sec', models.PositiveIntegerField(default=60, help_text='Минимум 10. Тексты, лимиты и сценарии применяются без перезапуска.', verbose_name='Период перечитывания настроек, сек')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=5, verbose_name='Лимит обращений в час')),
                ('max_text_length', models.PositiveIntegerField(default=2000, verbose_name='Макс. длина ответа, символов')),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Потолок Bot API на скачивание — 20 МБ.', verbose_name='Макс. размер вложения, МБ')),
                ('max_files_per_feedback', models.PositiveIntegerField(default=3, verbose_name='Макс. вложений в обращении')),
                ('allowed_file_types', models.CharField(default='jpg, jpeg, png, webp, pdf', help_text='Через запятую. Тип проверяется по содержимому, не по расширению.', max_length=255, verbose_name='Допустимые типы файлов')),
                ('retention_months', models.PositiveIntegerField(default=12, help_text='После срока обращения анонимизируются командой feedback_cleanup.', verbose_name='Срок хранения персональных данных, мес.')),
                ('privacy_policy_url', models.URLField(blank=True, default='https://gripline.ru/legal/privacy/', verbose_name='Ссылка на политику конфиденциальности')),
                ('restart_requested_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Перезапуск запрошен')),
                ('heartbeat_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последний heartbeat бота')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки бота обратной связи',
                'verbose_name_plural': 'Настройки бота обратной связи',
            },
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='Эмодзи')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('admin_topic_id', models.BigIntegerField(blank=True, help_text='Пусто = общий чат. Заполняется кнопкой «Создать темы по категориям».', null=True, verbose_name='ID темы в админ-чате')),
                ('deep_link_code', models.SlugField(blank=True, help_text='Короткий код (например, err) для ссылки t.me/<бот>?start=err_s_142. Только латиница/цифры.', max_length=10, verbose_name='Код для deep link')),
            ],
            options={
                'verbose_name': 'Категория обращений',
                'verbose_name_plural': 'Категории обращений',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Ключ')),
                ('text', models.TextField(verbose_name='Текст')),
                ('description', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты бота',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Ответы')),
                ('source_kind', models.CharField(blank=True, choices=[('stage', 'Этап'), ('pilot', 'Пилот'), ('track', 'Трасса')], max_length=10, verbose_name='Источник (тип)')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Источник (PK)')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_work', 'В работе'), ('done', 'Закрыто')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('admin_chat_message_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('admin_thread_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыто')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='Анонимизировано')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='website.feedbackcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('source_kind', models.CharField(blank=True, max_length=10)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.feedbackcategory')),
            ],
            options={
                'verbose_name': 'Черновик обращения',
                'verbose_name_plural': 'Черновики обращений',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=website.models._feedback_attachment_storage, upload_to=website.models._feedback_attachment_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.feedback')),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.feedbackdraft')),
            ],
            options={
                'verbose_name': 'Вложение обращения',
                'verbose_name_plural': 'Вложения обращений',
            },
        ),
        migrations.CreateModel(
            name='FeedbackModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=20, verbose_name='Канал')),
                ('external_user_id', models.CharField(help_text='Telegram user id (число).', max_length=64, verbose_name='ID пользователя в канале')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('role', models.CharField(choices=[('moderator', 'Модератор')], default='moderator', max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Модератор обращений',
                'verbose_name_plural': 'Модераторы обращений',
                'unique_together': {('channel', 'external_user_id')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'От пользователя'), ('out', 'От модератора')], max_length=3)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('admin_chat_message_id', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.feedback')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.feedbackmoderator')),
            ],
            options={
                'verbose_name': 'Сообщение по обращению',
                'verbose_name_plural': 'Сообщения по обращениям',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to='website.feedbackmoderator', verbose_name='Взял в работу'),
        ),
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=20)),
                ('external_user_id', models.CharField(max_length=64, verbose_name='ID в канале')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('privacy_notice_shown_at', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('ban_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина блокировки')),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
                'unique_together': {('channel', 'external_user_id')},
            },
        ),
        migrations.AddField(
            model_name='feedbackdraft',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='website.feedbackuser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='website.feedbackuser', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='FeedbackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='Порядок')),
                ('key', models.SlugField(help_text='Ключ ответа в карточке и JSON (например, where).', max_length=40, verbose_name='Ключ')),
                ('prompt_text', models.TextField(verbose_name='Вопрос пользователю')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('attachment', 'Вложение')], default='text', max_length=12, verbose_name='Тип')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('skip_button_text', models.CharField(blank=True, help_text='Пусто = пропуск невозможен.', max_length=40, verbose_name='Текст кнопки «Пропустить»')),
                ('skip_if_source_set', models.BooleanField(default=False, verbose_name='Пропускать, если обращение пришло по ссылке с объектом')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='website.feedbackcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Шаг сценария',
                'verbose_name_plural': 'Шаги сценария',
                'ordering': ['category', 'sort_order', 'id'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
