# Generated by Django 5.2.17 on 2026-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_feedback_bot_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcategory',
            name='widget_hint',
            field=models.CharField(blank=True, help_text='Короткая строка под названием в окне «Обратная связь» на сайте.', max_length=120, verbose_name='Подсказка в виджете на сайте'),
        ),
    ]
