# Generated by Django 5.2.17 on 2026-10-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_feedback_widget_hints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('stage', 'Этап (класс)'), ('pilot', 'Пилот'), ('track', 'Трасса'), ('champ', 'Чемпионат'), ('hub', 'Этап (общая страница)'), ('rating', 'Рейтинг (класс)')], max_length=10, verbose_name='Источник (тип)'),
        ),
        migrations.AlterField(
            model_name='feedbackcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=10, help_text='Чем меньше число, тем выше пункт. Порядок общий: в меню бота и в виджете «Обратная связь» на сайте. Удобно нумеровать с шагом 10 — чтобы потом вставить новый пункт между старыми.', verbose_name='Порядок'),
        ),
    ]
