# Generated by Django 5.2.17 on 2026-10-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_feedback_more_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Задача')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный запуск')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний сбой')),
                ('last_message', models.CharField(blank=True, max_length=255, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Запуск регулярной задачи',
                'verbose_name_plural': 'Запуски регулярных задач',
            },
        ),
        migrations.AddField(
            model_name='updatelog',
            name='race_results_count',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Результатов на момент обновления'),
        ),
        migrations.CreateModel(
            name='AdminDashboardVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField()),
                ('since', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_visit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Визит на главную админки',
                'verbose_name_plural': 'Визиты на главную админки',
            },
        ),
    ]
