# Generated by Django 5.2.17 on 2026-10-06 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_admin_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackbotsettings',
            name='digest_enabled',
            field=models.BooleanField(default=True, help_text='Сводка уходит в админ-чат: что требует внимания, что нового за сутки, состояние системы.', verbose_name='Утренняя сводка включена'),
        ),
        migrations.AddField(
            model_name='feedbackbotsettings',
            name='digest_last_sent_on',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Сводка последний раз отправлена'),
        ),
        migrations.AddField(
            model_name='feedbackbotsettings',
            name='digest_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='По московскому времени. Проверка идёт каждые 10 минут, поэтому сводка придёт в ближайшие 10 минут после этого времени.', verbose_name='Время отправки сводки'),
        ),
    ]
