# Generated by Django 5.2.17 on 2026-10-07 13:37

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_feedback_digest_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Пусто — стандартное название поля.', max_length=80, verbose_name='Подпись')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица')),
                ('mode', models.CharField(choices=[('range', 'Диапазон: минимум, максимум, шаг'), ('list', 'Список')], default='range', max_length=5, verbose_name='Значения')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Минимум')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Максимум')),
                ('step', models.DecimalField(blank=True, decimal_places=3, help_text='Например 1, 0.25 или 0.5.', max_digits=9, null=True, verbose_name='Шаг')),
                ('prefix', models.CharField(blank=True, help_text='Например K → K46, K47…', max_length=10, verbose_name='Префикс')),
                ('options_text', models.TextField(blank=True, help_text='По одному значению в строке.', verbose_name='Список значений')),
                ('default_value', models.CharField(blank=True, max_length=40, verbose_name='По умолчанию')),
                ('allow_custom', models.BooleanField(default=True, verbose_name='Можно своё значение («Другое…»)')),
                ('key', models.CharField(choices=[('hub_width_mm', 'Ширина ступицы, мм'), ('pinion_teeth', 'Пиньон, зубья'), ('sprocket_teeth', 'Звёздочка, зубья'), ('spacer', 'Проставки (кольца)')], max_length=30, unique=True, verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Параметр приложения',
                'verbose_name_plural': 'Параметры приложения',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='chassis',
            name='show_in_app',
            field=models.BooleanField(default=False, help_text='Запись попадёт в мобильное приложение GripLine SetupKart после публикации справочников (меню «Приложение» → «Публикация»). Без галочки — только на сайте.', verbose_name='Показывать в приложении'),
        ),
        migrations.AddField(
            model_name='engine',
            name='app_family',
            field=models.CharField(blank=True, choices=[('rotax', 'Rotax'), ('iame', 'IAME'), ('vortex', 'Vortex'), ('tm', 'TM'), ('honda', 'Honda'), ('briggs', 'Briggs'), ('other', 'Другое')], help_text='Нужно, чтобы сетапы из оригинального приложения (марка + категория) сопоставлялись с этим двигателем.', max_length=20, verbose_name='Семейство (для импорта .kart)'),
        ),
        migrations.AddField(
            model_name='engine',
            name='app_race_classes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Классы, которые пользователь сможет выбрать с этим двигателем.', related_name='app_engines', to='website.raceclass', verbose_name='Классы в приложении'),
        ),
        migrations.AddField(
            model_name='engine',
            name='show_in_app',
            field=models.BooleanField(default=False, help_text='Запись попадёт в мобильное приложение GripLine SetupKart после публикации справочников (меню «Приложение» → «Публикация»). Без галочки — только на сайте.', verbose_name='Показывать в приложении'),
        ),
        migrations.AddField(
            model_name='track',
            name='show_in_app',
            field=models.BooleanField(default=False, help_text='Запись попадёт в мобильное приложение GripLine SetupKart после публикации справочников (меню «Приложение» → «Публикация»). Без галочки — только на сайте.', verbose_name='Показывать в приложении'),
        ),
        migrations.AddField(
            model_name='tyrebrand',
            name='show_in_app',
            field=models.BooleanField(default=False, help_text='Запись попадёт в мобильное приложение GripLine SetupKart после публикации справочников (меню «Приложение» → «Публикация»). Без галочки — только на сайте.', verbose_name='Показывать в приложении'),
        ),
        migrations.CreateModel(
            name='AppCatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True, verbose_name='Версия')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('payload', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Версия справочников приложения',
                'verbose_name_plural': 'Версии справочников приложения',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='AppEngineSparkPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=60, verbose_name='Свеча')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('engine', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_spark_plugs', to='website.engine')),
            ],
            options={
                'verbose_name': 'Свеча',
                'verbose_name_plural': 'Свечи',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppEngineField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, help_text='Пусто — стандартное название поля.', max_length=80, verbose_name='Подпись')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица')),
                ('mode', models.CharField(choices=[('range', 'Диапазон: минимум, максимум, шаг'), ('list', 'Список')], default='range', max_length=5, verbose_name='Значения')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Минимум')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Максимум')),
                ('step', models.DecimalField(blank=True, decimal_places=3, help_text='Например 1, 0.25 или 0.5.', max_digits=9, null=True, verbose_name='Шаг')),
                ('prefix', models.CharField(blank=True, help_text='Например K → K46, K47…', max_length=10, verbose_name='Префикс')),
                ('options_text', models.TextField(blank=True, help_text='По одному значению в строке.', verbose_name='Список значений')),
                ('default_value', models.CharField(blank=True, max_length=40, verbose_name='По умолчанию')),
                ('allow_custom', models.BooleanField(default=True, verbose_name='Можно своё значение («Другое…»)')),
                ('key', models.CharField(choices=[('main_jet', 'Главный жиклёр'), ('main_jet_in', 'Главный жиклёр (дюймы)'), ('idle_jet', 'Жиклёр холостого хода'), ('needle', 'Игла'), ('mixing_tube', 'Смесительная трубка'), ('throttle_slide', 'Золотник'), ('idle_turns', 'Холостой ход'), ('air_screw_turns', 'Воздушный винт'), ('needle_position', 'Положение иглы (1 — бедная … 5 — богатая)'), ('needle_clip', 'Клипса иглы'), ('needle_high', 'Винт High (Tillotson)'), ('needle_low', 'Винт Low (Tillotson)'), ('plug_gap_mm', 'Зазор свечи, мм')], max_length=30, verbose_name='Поле')),
                ('engine', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_fields', to='website.engine')),
            ],
            options={
                'verbose_name': 'Поле карбюратора',
                'verbose_name_plural': 'Поля карбюратора',
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('engine', 'key'), name='app_engine_field_unique_key')],
            },
        ),
        migrations.CreateModel(
            name='AppSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=30, verbose_name='Поле')),
                ('value', models.CharField(max_length=60, verbose_name='Значение')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Сколько раз прислали')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Впервые')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('added', 'Добавлено в справочник'), ('hidden', 'Скрыто')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_suggestions', to='website.engine', verbose_name='Двигатель')),
            ],
            options={
                'verbose_name': 'Предложение пользователей',
                'verbose_name_plural': 'Предложения пользователей',
                'ordering': ['-count', '-last_seen'],
                'constraints': [models.UniqueConstraint(fields=('field_key', 'engine', 'value'), name='app_suggestion_unique')],
            },
        ),
    ]
