# Generated by Django 5.2.17 on 2026-10-07 14:29

from django.db import migrations, models


def create_app_category(apps, schema_editor):
    # Категория обращений из приложения: своя тема в админ-чате, в меню бота и виджете сайта её нет.
    FeedbackCategory = apps.get_model('website', 'FeedbackCategory')
    FeedbackCategory.objects.get_or_create(
        slug='setupkart', defaults={'title': 'GripLine SetupKart', 'emoji': '📱', 'is_active': False},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_setupkart_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmoderator',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('setupkart', 'Приложение SetupKart')], default='telegram', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='feedbackuser',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('setupkart', 'Приложение SetupKart')], default='telegram', max_length=20),
        ),
        migrations.RunPython(create_app_category, migrations.RunPython.noop),
    ]
