# Generated by Django 5.2.17 on 2026-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_rename_spec_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='aliases',
            field=models.CharField(blank=True, default='', help_text='Другие написания через запятую, например «Cosmik». Импорт протоколов находит шасси и по ним, приложение подставляет основное название, если пользователь ввёл синоним через «Другое…».', max_length=255, verbose_name='Синонимы'),
        ),
    ]
