# Generated by Django 5.2.17 on 2026-10-08 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_chassis_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, help_text='Как часто открытое приложение проверяет справочник и трассы и отправляет предложения и обратную связь. Для проверки — 1–5 минут, в работе — 60 и больше. Новое значение приложение узнает при следующей связи.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Интервал связи приложения с сайтом, мин.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Связь приложения с сайтом',
                'verbose_name_plural': 'Связь приложения с сайтом',
            },
        ),
        migrations.AddField(
            model_name='appsuggestion',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='appsuggestion',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
