# Generated by Django 5.2.17 on 2026-10-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0059_app_sync_settings_track_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppChassisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Взрослое», «Детское малое».', max_length=60, unique=True, verbose_name='Тип шасси')),
                ('front_x', models.FloatField(blank=True, null=True, verbose_name='Левое переднее колесо, x')),
                ('front_y', models.FloatField(blank=True, null=True, verbose_name='Левое переднее колесо, y')),
                ('rear_x', models.FloatField(blank=True, null=True, verbose_name='Левое заднее колесо, x')),
                ('rear_y', models.FloatField(blank=True, null=True, verbose_name='Левое заднее колесо, y')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка шасси (приложение)',
                'verbose_name_plural': 'Картинки шасси (приложение)',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='raceclass',
            name='app_chassis_image',
            field=models.ForeignKey(blank=True, help_text='Тип шасси, картинка которого показывается в приложении GripLine SetupKart для этого класса. Пусто — встроенная схема. Картинки: «Техника» → «Картинки шасси».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_classes', to='website.appchassisimage', verbose_name='Картинка шасси в приложении'),
        ),
    ]
