# Generated by Django 5.2.17 on 2026-10-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0060_app_chassis_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHelpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('steering_column_hole', 'Рулевая колонка: отверстия')], max_length=40, unique=True, verbose_name='Поле')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка-подсказка (приложение)',
                'verbose_name_plural': 'Картинки-подсказки (приложение)',
                'ordering': ['key'],
            },
        ),
    ]
