# Generated by Django 5.2.17 on 2026-10-08 15:53

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0061_app_help_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTyreCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Как подписать плитку: «Мягкая», «Средняя», «Дождь»…', max_length=40, verbose_name='Название')),
                ('kind', models.CharField(choices=[('slick', 'Слик'), ('wet', 'Дождь'), ('intermediate', 'Промежуточные')], default='slick', max_length=20, verbose_name='Тип')),
                ('brand', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_compounds', to='website.tyrebrand')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Состав шины (приложение)',
                'verbose_name_plural': 'Составы шин (приложение)',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
