# Generated by Django 5.2.17 on 2026-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_app_tyre_compounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsyncsettings',
            name='about_text',
            field=models.TextField(blank=True, default='GripLine SetupKart сделали в Gripline — проекте о российском картинге. На gripline.ru собраны результаты соревнований, рейтинги пилотов и шасси, календарь этапов и статьи о настройке карта.\n\nПриложение — для механиков и пилотов: быстро записать настройку прямо на трассе, сравнить с прошлыми сессиями и не потерять то, что сработало. Есть идея или нашли ошибку — напишите нам.', help_text='Показывается в приложении внизу экрана «О приложении», под логотипом Gripline.', verbose_name='Текст «О нас»'),
        ),
        migrations.AddField(
            model_name='appsyncsettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='gripline.ru@yandex.ru', max_length=254, verbose_name='E-mail для связи'),
        ),
        migrations.AddField(
            model_name='appsyncsettings',
            name='contact_telegram',
            field=models.CharField(blank=True, default='@gripline_support', help_text='@имя или ссылка t.me/…; пусто — строка в приложении не показывается.', max_length=64, verbose_name='Telegram для связи'),
        ),
        migrations.AddField(
            model_name='appsyncsettings',
            name='site_url',
            field=models.URLField(default='https://gripline.ru', help_text='Ссылка в «О приложении».', verbose_name='Сайт'),
        ),
    ]
