# Generated by Django 5.2.17 on 2026-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_app_about_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphelpimage',
            name='key',
            field=models.CharField(choices=[('steering_column_hole', 'Рулевая колонка: отверстия'), ('needle_position', 'Карбюратор: положение иглы')], max_length=40, unique=True, verbose_name='Поле'),
        ),
    ]
