# Generated by Django 5.2.17 on 2026-10-09 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0064_app_help_image_needle'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='app_carburetor_image',
            field=models.ForeignKey(blank=True, help_text='Показывается в приложении по центру раздела «Карбюратор», над настройками. Своё фото или схема (не из других приложений). Пусто — раздел без картинки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Картинка карбюратора'),
        ),
    ]
