# Generated by Django 5.2.12 on 2026-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
        ('website', '0006_adfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='competition_types',
            field=models.ManyToManyField(blank=True, help_text='Типы соревнований (Кубок, Первенство, Чемпионат и т.д.)', to='website.competitiontype'),
        ),
    ]
