# Generated by Django 5.2.12 on 2026-04-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_organizerprofile_competition_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerprofile',
            name='competition_types',
        ),
    ]
