# Generated by Django 5.2.12 on 2026-04-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_remove_organizerprofile_competition_types'),
        ('website', '0006_adfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='default_tyre',
            field=models.ForeignKey(blank=True, help_text='Шина по умолчанию для всех классов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.tyre'),
        ),
        migrations.AddField(
            model_name='championship',
            name='race_classes',
            field=models.ManyToManyField(blank=True, help_text='Классы, которые участвуют в чемпионате', to='website.raceclass'),
        ),
    ]
