# Generated by Django 5.2.11 on 2026-03-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverclaimadminpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverclaim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка пилота', 'verbose_name_plural': 'Заявки пилотов'},
        ),
        migrations.DeleteModel(
            name='DriverClaimAdminPage',
        ),
    ]
