# Generated by Django 5.2.12 on 2026-07-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_roles_team_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauthsettings',
            name='vk_client_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='VK Client ID'),
        ),
        migrations.AddField(
            model_name='socialauthsettings',
            name='vk_client_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='VK Client Secret'),
        ),
        migrations.DeleteModel(
            name='YandexSocialAuth',
        ),
    ]
