# Generated by Django 5.2.17 on 2026-10-07 06:24

from django.db import migrations, models


def mark_existing_verified(apps, schema_editor):
    # Раньше поле нигде не использовалось (default=False, True — только у демо-аккаунтов).
    # Все существующие пользователи — установленные, подтверждение им не требуется.
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(email_verified=False).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_socialauthsettings_vk_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_team_name',
            field=models.CharField(blank=True, help_text='Хранится до подтверждения email и выбора команды; нужно, чтобы ссылку можно было открыть в другом браузере.', max_length=255, verbose_name='Название команды из регистрации'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=True, help_text='False — только у новых регистраций по email до перехода по ссылке из письма. Не связано с is_active: is_active=False значит «заблокирован», и ссылка из письма его не снимает.', verbose_name='Email подтверждён'),
        ),
        migrations.RunPython(mark_existing_verified, migrations.RunPython.noop),
    ]
