[program:gripline_admin_bot]
command=/home/{{user}}/{{project_path}}/venv/bin/python /home/{{user}}/{{project_path}}/manage.py run_bot
directory=/home/{{user}}/{{project_path}}
user={{user}}
autostart=true
autorestart=true
stderr_logfile=/var/log/gripline/admin_bot.err.log
stdout_logfile=/var/log/gripline/admin_bot.out.log
environment=PATH="/home/{{user}}/{{project_path}}/venv/bin:%(ENV_PATH)s"

[program:gripline_user_bot]
command=/home/{{user}}/{{project_path}}/venv/bin/python /home/{{user}}/{{project_path}}/manage.py run_user_bot
directory=/home/{{user}}/{{project_path}}
user={{user}}
autostart=true
autorestart=true
stderr_logfile=/var/log/gripline/user_bot.err.log
stdout_logfile=/var/log/gripline/user_bot.out.log
environment=PATH="/home/{{user}}/{{project_path}}/venv/bin:%(ENV_PATH)s"
