"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Загружаем .env как можно раньше, чтобы env-переменные были доступны
# при определении DATABASES ниже (независимо от порядка импорта в prod/dev)
load_dotenv(BASE_DIR / ".env")

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.postgres',
    'wagtail_modeladmin',
    'wagtailmarkdown',
    'organizers.apps.OrganizersConfig',
    'applications.apps.ApplicationsConfig',
    'demo.apps.DemoConfig',
    # This project
    "website.apps.WebsiteConfig",
    # Wagtail CRX (CodeRed Extensions)
    "coderedcms",
    "django_bootstrap5",
    "import_export",
    "modelcluster",
    "taggit",
    "wagtailcache",
    "wagtailseo",
    # Social auth
    "social_django",
    # Rate-limit/lockout на login-формы (admin + accounts/teams/organizers)
    "axes",
    # Wagtail
    "wagtail.contrib.forms",
    "accounts",
    "teams",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail",
    "wagtail.contrib.settings",
    "wagtail.contrib.table_block",
    "wagtail.admin",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
]

MIDDLEWARE = [
    # Save pages to cache. Must be FIRST.
    "wagtailcache.cache.UpdateCacheMiddleware",
    # Common functionality
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Security
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Должен идти после AuthenticationMiddleware (требование django-axes) и до
    # FetchFromCacheMiddleware — но т.к. wagtailcache не кэширует POST-запросы
    # (сами login-вьюхи), порядок относительно него не критичен на практике.
    "axes.middleware.AxesMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "mysite.security.ContentSecurityPolicyReportOnlyMiddleware",
    # CMS functionality
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    # Fetch from cache. Must be LAST.
    "wagtailcache.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
    }
}

# Токен бота для анонс-постинга в Telegram-канал (см. website/telegram.py).
# Секрет — только из окружения, никогда не в БД/админке.
TELEGRAM_ANNOUNCE_BOT_TOKEN = os.getenv("TELEGRAM_ANNOUNCE_BOT_TOKEN")

# Прокси для запросов к Telegram Bot API — нужен там, где хостер/провайдер
# блокирует прямые соединения к api.telegram.org (напр. на проде, TCP:443
# до Telegram глушится на уровне сети, хотя ICMP и остальной интернет
# работают). Локально не задан — прямое соединение работает. Формат:
# socks5h://127.0.0.1:10808 (локальный SOCKS5 от Xray, поднятого на сервере).
TELEGRAM_PROXY_URL = os.getenv("TELEGRAM_PROXY_URL")

# Токен бота для анонс-постинга в канал MAX (см. website/max.py).
# Секрет — только из окружения, никогда не в БД/админке.
MAX_ANNOUNCE_BOT_TOKEN = os.getenv("MAX_ANNOUNCE_BOT_TOKEN")

# Базовый URL MAX Bot API — вынесен в env, а не захардкожен: на момент
# написания в документации фигурируют варианты домена с "2" и без —
# уточнение не должно требовать деплоя кода. MAX доступен с прод-сервера
# напрямую, прокси (в отличие от Telegram) не нужен.
MAX_API_BASE_URL = os.getenv("MAX_API_BASE_URL", "https://platform-api2.max.ru")

# Токен доступа для анонс-постинга в сообщество VK (см. website/vk.py).
# Секрет — только из окружения, никогда не в БД/админке. Получается либо
# ключом доступа сообщества (Управление → Работа с API), либо через
# OAuth Standalone-приложения — см. ручные шаги в плане деплоя.
VK_ANNOUNCE_ACCESS_TOKEN = os.getenv("VK_ANNOUNCE_ACCESS_TOKEN")

# Версия VK API — обязательный параметр в каждом запросе, вынесена в env,
# чтобы обновлять без деплоя кода. VK доступен с прод-сервера напрямую,
# прокси не нужен (российский сервис, та же логика, что MAX).
VK_API_VERSION = os.getenv("VK_API_VERSION", "5.199")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        # Никогда не логировать TELEGRAM_ANNOUNCE_BOT_TOKEN и полный текст
        # исключений без фильтрации — см. website/telegram.py::send_to_telegram.
        "telegram_announce": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Никогда не логировать MAX_ANNOUNCE_BOT_TOKEN и полный текст
        # исключений без фильтрации — см. website/max.py::send_to_max.
        "max_announce": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Никогда не логировать VK_ANNOUNCE_ACCESS_TOKEN и полный текст
        # исключений без фильтрации — см. website/vk.py::send_to_vk.
        "vk_announce": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Всплески обращений с одного IP на мутирующие эндпоинты /balance/ —
        # см. website/services/balance_limits.py::balance_ratelimit (ТЗ §12).
        "balance.ratelimit": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # Отчёты Content-Security-Policy-Report-Only — см. website/csp_views.py.
        # Наблюдательная фаза (security-аудит, п.5): `journalctl -u gripline
        # | grep CSP-VIOLATION` покажет всё, что нарушило бы политику, если бы
        # она была включена всерьёз.
        "gripline.csp": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Login

LOGIN_URL = "wagtailadmin_login"
LOGIN_REDIRECT_URL = "wagtailadmin_home"


# Wagtail settings

WAGTAIL_SITE_NAME = "mysite"

WAGTAIL_ENABLE_UPDATE_CHECK = False

WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]


# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://localhost"


# Tags

TAGGIT_CASE_INSENSITIVE = True


# Sets default for primary key IDs
# See https://docs.djangoproject.com/en/5.2/ref/models/fields/#bigautofield
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'gripline.ru@yandex.ru'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = 5


# Базовый URL сайта для ссылок в письмах
BASE_URL = 'http://127.0.0.1:8000'  # для продакшена заменить на реальный домен


# Форма предпросмотра импорта результатов (website/import_utils.py) генерирует
# ~18 полей на строку CSV — при классах с 60+ пилотами дефолтный лимит Django (1000)
# превышается, и запрос падает с Bad Request (400) без пояснения.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


# ── Social Auth (social-auth-app-django) ──────────────────────────────────────

AUTHENTICATION_BACKENDS = [
    # Должен идти первым (требование django-axes) — перехватывает
    # authenticate() раньше остальных backend'ов и блокирует попытку,
    # если username+IP уже превысили AXES_FAILURE_LIMIT.
    'axes.backends.AxesBackend',
    'accounts.backends.GriplineYandexOAuth2',
    'accounts.backends.GriplineVKID',
    'django.contrib.auth.backends.ModelBackend',
]

# ── django-axes: rate-limit/lockout на login-формы ────────────────────────────
# Покрывает и /admin/login/ (стандартный AuthenticationForm), и кастомные
# login_view в accounts/teams/organizers — все они вызывают authenticate()
# с передачей request, что и требуется axes для трекинга. Yandex/VK OAuth не
# затрагиваются — там нет пары username/password, authenticate() не вызывается.
AXES_FAILURE_LIMIT = 5
# Блокировка по паре (username, ip_address), не по одному IP: даже с верным
# определением IP (см. AXES_CLIENT_IP_CALLABLE ниже) блокировка только по IP
# задела бы всех пользователей за одним NAT/мобильным оператором, а только по
# username — сделала бы возможным DoS чужого аккаунта подбором пароля с любого
# IP. Комбинация — стандартная рекомендация django-axes для этого случая.
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
# Автоматическая разблокировка через час — блокировка не должна быть вечной
# для случайно оговорившегося легитимного пользователя.
AXES_COOLOFF_TIME = 1  # часы
# Успешный вход сбрасывает счётчик неудачных попыток для этой пары.
AXES_RESET_ON_SUCCESS = True
# Сайт живёт за nginx-реверс-прокси на том же хосте (gunicorn слушает только
# 127.0.0.1:8000) — без этого axes видел бы у ВСЕХ посетителей один и тот же
# IP (127.0.0.1, адрес nginx), и блокировка по IP+username превратилась бы в
# блокировку по username сразу для всех. django-ipware для этого не подходит
# (рассчитан на список заранее известных доверенных прокси-IP, а не «доверяй
# последнему хопу») — используем свой callable, см. docstring в mysite/security.py.
AXES_CLIENT_IP_CALLABLE = 'mysite.security.get_client_ip'

# ── Content-Security-Policy (Report-Only, наблюдательная фаза) ───────────────
# Пункт 5 приоритетного списка security-аудита. Источники собраны grep'ом по
# реальным шаблонам (<script src=, <link href=, @import url() и т.п.) —
# НЕ по памяти/документации. Полный разбор — см. коммит, добавляющий CSP.
#
# 'unsafe-inline' в script-src/style-src — сознательный компромисс версии 1:
# инлайн-скрипты и style="" используются по всему сайту (аналитика, VK ID
# виджет, десятки шаблонов), и без этого допущения Report-Only просто завалил
# бы логи тысячами ожидаемых срабатываний вместо того, чтобы показать что-то
# новое. Даже с этим допущением connect-src/img-src/frame-src остаются
# строгими — это перекрывает главный практический сценарий XSS (эксфильтрация
# данных на чужой домен через инжект скрипта/пикселя), просто не поднимает
# защиту до уровня «чистого» nonce/hash CSP. Ужесточение — отдельная задача
# после недели наблюдения за отчётами.
#
# Дополнено по итогам первого QA-прогона в Report-Only (тот же день) —
# реальный трафик высветил источники, которых не было в grep по git-коду:
# - Google Analytics/GTM (googletagmanager.com, google-analytics.com) —
#   подключены НЕ из кода, а из AnalyticsSettings.gtm_id/ga_g_tracking_id
#   (Wagtail admin, значение в БД) — поэтому grep по репозиторию их не нашёл.
# - mc.yandex.com (не только .ru) + wss://mc.yandex.{ru,com}/solid.ws —
#   Яндекс.Метрика в реальности бьёт по обоим TLD и открывает WebSocket для
#   вебвизора (записи сессий).
# - core-renderer-tiles.maps.yandex.net — реальный сервер тайлов карты
#   (api-maps.yandex.ru — только загрузчик SDK, тайлы — отдельный домен).
# - yastatic.net — статика Яндекса (JS Метрики/Карт, курсоры карты).
# - id.vk.ru / login.vk.ru — VK ID SDK при реальном запросе к VK (One Tap,
#   попап логина) стучится не только на unpkg.com за самим скриптом.
CSP_REPORT_ONLY_DIRECTIVES = {
    'default-src': ["'self'"],
    'script-src': [
        "'self'", "'unsafe-inline'",
        'https://mc.yandex.ru',              # Яндекс.Метрика (base.html, app_base.html)
        'https://mc.yandex.com',             # Метрика — реальные хиты и на .com
        'https://yastatic.net',              # статика Метрики/Карт
        'https://cdn.jsdelivr.net',          # Chart.js (driver/chassis/compare/weather-impact)
        'https://code.jquery.com',           # jQuery (compare_drivers.html)
        'https://cdnjs.cloudflare.com',      # fuse.js (админка, import_preview.html)
        'https://api-maps.yandex.ru',        # Яндекс.Карты (pulse_index_page.html)
        'https://unpkg.com',                 # VK ID SDK (_social_auth_buttons.html)
        'https://www.googletagmanager.com',  # GTM (AnalyticsSettings.gtm_id, из БД)
    ],
    'style-src': ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
    'font-src': ["'self'", 'https://fonts.gstatic.com', 'data:'],
    'img-src': [
        "'self'", 'data:',
        'https://mc.yandex.ru', 'https://mc.yandex.com',
        'https://core-renderer-tiles.maps.yandex.net',  # тайлы Яндекс.Карт
        'https://log.api-maps.yandex.ru',
        'https://yastatic.net',
    ],
    'connect-src': [
        "'self'",
        'https://mc.yandex.ru', 'https://mc.yandex.com',
        'wss://mc.yandex.ru', 'wss://mc.yandex.com',    # вебвизор Метрики
        'https://region1.google-analytics.com', 'https://www.google-analytics.com',
        'https://id.vk.ru',                             # VK ID One Tap
    ],
    'frame-src': ["'self'", 'https://mc.yandex.ru', 'https://id.vk.ru', 'https://login.vk.ru'],
    'object-src': ["'none'"],
    'base-uri': ["'self'"],
    'frame-ancestors': ["'self'"],
    'report-uri': ['/csp-report/'],
}

# Credentials are stored in DB (SocialAuthSettings) and read by get_key_and_secret() of each backend
SOCIAL_AUTH_YANDEX_OAUTH2_SCOPE = ['login:email', 'login:info']
# VK ID: scope задан прямо в GriplineVKID.DEFAULT_SCOPE.
# Email придёт, только если он подтверждён у пользователя в самом VK —
# у части пользователей его нет, тогда email в ответе будет пустым.

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'accounts.pipeline.set_unusable_password',
    'accounts.pipeline.setup_onboarding',
)

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/accounts/profile/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/'
SOCIAL_AUTH_LOGOUT_REDIRECT_URL = '/choose-role/'
# 'balance_next' — НЕ 'next': PSA уже резервирует 'next' (django.contrib.auth.
# REDIRECT_FIELD_NAME) для своего встроенного redirect_value в
# social_core.actions.do_auth/do_complete — передав ?next=/balance/ мы бы
# получили редирект ПРЯМО на /balance/ для любого пользователя, включая
# только что созданного (минуя accounts/pipeline.py::setup_onboarding →
# формы заявки пилота). Свой ключ 'balance_next' обходит эту встроенную
# логику и обрабатывается вручную в pipeline.py + views.py::profile().
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['role', 'pilot_id', 'team_id', 'team_name', 'balance_next']

SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False  # set True in prod settings
