"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Загружаем .env как можно раньше, чтобы env-переменные были доступны
# при определении DATABASES ниже (независимо от порядка импорта в prod/dev)
load_dotenv(BASE_DIR / ".env")

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.postgres',
    'wagtail_modeladmin',
    'wagtailmarkdown',
    'organizers.apps.OrganizersConfig',
    'applications.apps.ApplicationsConfig',
    'demo.apps.DemoConfig',
    # This project
    "website.apps.WebsiteConfig",
    # Wagtail CRX (CodeRed Extensions)
    "coderedcms",
    "django_bootstrap5",
    "import_export",
    "modelcluster",
    "taggit",
    "wagtailcache",
    "wagtailseo",
    # Social auth
    "social_django",
    # Wagtail
    "wagtail.contrib.forms",
    "accounts",
    "teams",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail",
    "wagtail.contrib.settings",
    "wagtail.contrib.table_block",
    "wagtail.admin",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
]

MIDDLEWARE = [
    # Save pages to cache. Must be FIRST.
    "wagtailcache.cache.UpdateCacheMiddleware",
    # Common functionality
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.common.CommonMiddleware",
    # Security
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # CMS functionality
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    # Fetch from cache. Must be LAST.
    "wagtailcache.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
    }
}

# Токен бота для анонс-постинга в Telegram-канал (см. website/telegram.py).
# Секрет — только из окружения, никогда не в БД/админке.
TELEGRAM_ANNOUNCE_BOT_TOKEN = os.getenv("TELEGRAM_ANNOUNCE_BOT_TOKEN")

# Прокси для запросов к Telegram Bot API — нужен там, где хостер/провайдер
# блокирует прямые соединения к api.telegram.org (напр. на проде, TCP:443
# до Telegram глушится на уровне сети, хотя ICMP и остальной интернет
# работают). Локально не задан — прямое соединение работает. Формат:
# socks5h://127.0.0.1:10808 (локальный SOCKS5 от Xray, поднятого на сервере).
TELEGRAM_PROXY_URL = os.getenv("TELEGRAM_PROXY_URL")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        # Никогда не логировать TELEGRAM_ANNOUNCE_BOT_TOKEN и полный текст
        # исключений без фильтрации — см. website/telegram.py::send_to_telegram.
        "telegram_announce": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Login

LOGIN_URL = "wagtailadmin_login"
LOGIN_REDIRECT_URL = "wagtailadmin_home"


# Wagtail settings

WAGTAIL_SITE_NAME = "mysite"

WAGTAIL_ENABLE_UPDATE_CHECK = False

WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]


# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://localhost"


# Tags

TAGGIT_CASE_INSENSITIVE = True


# Sets default for primary key IDs
# See https://docs.djangoproject.com/en/5.2/ref/models/fields/#bigautofield
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'gripline.ru@yandex.ru'
EMAIL_HOST_PASSWORD = '5a33af98b71f93708a4179b652a6baeb'  # ваш пароль приложения
EMAIL_TIMEOUT = 5


# Базовый URL сайта для ссылок в письмах
BASE_URL = 'http://127.0.0.1:8000'  # для продакшена заменить на реальный домен


# Форма предпросмотра импорта результатов (website/import_utils.py) генерирует
# ~18 полей на строку CSV — при классах с 60+ пилотами дефолтный лимит Django (1000)
# превышается, и запрос падает с Bad Request (400) без пояснения.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


# ── Social Auth (social-auth-app-django) ──────────────────────────────────────

AUTHENTICATION_BACKENDS = [
    'accounts.backends.GriplineYandexOAuth2',
    'accounts.backends.GriplineVKID',
    'django.contrib.auth.backends.ModelBackend',
]

# Credentials are stored in DB (SocialAuthSettings) and read by get_key_and_secret() of each backend
SOCIAL_AUTH_YANDEX_OAUTH2_SCOPE = ['login:email', 'login:info']
# VK ID: scope задан прямо в GriplineVKID.DEFAULT_SCOPE.
# Email придёт, только если он подтверждён у пользователя в самом VK —
# у части пользователей его нет, тогда email в ответе будет пустым.

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'accounts.pipeline.set_unusable_password',
    'accounts.pipeline.setup_onboarding',
)

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/accounts/profile/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/'
SOCIAL_AUTH_LOGOUT_REDIRECT_URL = '/choose-role/'
SOCIAL_AUTH_FIELDS_STORED_IN_SESSION = ['role', 'pilot_id', 'team_id', 'team_name']

SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False  # set True in prod settings
