"""
Одноразовая, но безопасно перезапускаемая (идемпотентная) команда:
транслитерирует кириллические slug уже существующих Wagtail-страниц в
ASCII — приводит их к тому же виду, что и новые страницы (см.
website/models.py::TransliteratedSlugMixin), и создаёт redirect со
старого URL на новый, чтобы уже расшаренные ссылки (в соцсетях, у
поисковиков) не превращались в 404.

Запуск: python manage.py transliterate_existing_slugs [--dry-run]
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils.text import slugify
from unidecode import unidecode
from wagtail.contrib.redirects.models import Redirect
from wagtail.models import Page, Site


def _is_ascii(value):
    try:
        value.encode('ascii')
        return True
    except UnicodeEncodeError:
        return False


class Command(BaseCommand):
    help = "Транслитерирует кириллические slug существующих страниц в ASCII, создаёт redirect со старых URL."

    def add_arguments(self, parser):
        parser.add_argument(
            '--dry-run', action='store_true',
            help='Показать, что будет изменено, без сохранения',
        )

    def handle(self, *args, **options):
        dry_run = options['dry_run']
        site = Site.objects.filter(is_default_site=True).first()

        non_ascii_pages = [p for p in Page.objects.all().specific() if not _is_ascii(p.slug)]
        self.stdout.write(f"Найдено страниц с нелатинским slug: {len(non_ascii_pages)}")

        for page in non_ascii_pages:
            old_slug = page.slug
            old_url = page.url  # относительный URL, ещё со старым slug — используется для redirect

            if old_url == '/':
                # Корневая страница сайта — её URL всегда "/" независимо от
                # slug, менять нечего, а redirect "/" -> "/" бессмыслен.
                self.stdout.write(f"  [{page.pk}] '{old_slug}' -> пропускаю (страница-корень сайта, URL всегда '/')")
                continue

            base_slug = slugify(unidecode(old_slug))
            if not base_slug:
                self.stdout.write(self.style.WARNING(
                    f"  [{page.pk}] '{old_slug}' -> транслитерация дала пустую строку, пропускаю"
                ))
                continue

            # Переиспользуем встроенный в Wagtail механизм проверки уникальности
            # slug среди страниц-соседей (тот же, что использует сам Page.save()).
            new_slug = page._get_autogenerated_slug(base_slug)

            self.stdout.write(f"  [{page.pk}] '{old_slug}' -> '{new_slug}'  ({old_url})")

            if dry_run:
                continue

            with transaction.atomic():
                page.slug = new_slug
                page.save()

                if old_url:
                    Redirect.objects.get_or_create(
                        old_path=Redirect.normalise_path(old_url),
                        site=site,
                        defaults={
                            'redirect_page': page,
                            'is_permanent': True,
                        },
                    )

        self.stdout.write(self.style.SUCCESS(
            'Готово' + (' (dry-run, изменения не сохранены)' if dry_run else '')
        ))
