# Generated by Django 5.2.11 on 2026-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='ID пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('email', models.EmailField(help_text='Email, который пользователь указал при регистрации', max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'indexes': [models.Index(fields=['telegram_id'], name='tg_user_bot_telegra_e3db8d_idx'), models.Index(fields=['email'], name='tg_user_bot_email_825a49_idx')],
            },
        ),
    ]
